version: '3'

volumes:
  postgres_data_dev:
      driver: local
  upload_dev:
      driver: local
  heatmap_dev:
      driver: local

services:

   aiserver_dev:
      build: ./aiserver
      ports:
         - "50052:50052"
      volumes:
         - upload_dev:/app/uploaddir 
         - ${PWD}/models_dev:/app/models 
         - heatmap_dev:/app/heatmapdir 

   aiweb_dev:
      build: ./aiweb
      ports:
         - "3001:3001"
      environment:
         - DEBUG=serverapp
      volumes:
         - upload_dev:/app/uploaddir 
         - heatmap_dev:/app/heatmapdir 

   postgres_dev:
      image: postgres
      volumes:
         - postgres_data_dev:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

   keycloak_dev:
      image: jboss/keycloak
      environment:
         DB_VENDOR: POSTGRES
         DB_ADDR: postgres_dev
         DB_DATABASE: keycloak
         DB_USER: keycloak
         DB_SCHEMA: public
         DB_PASSWORD: password
         KEYCLOAK_USER: admin
         KEYCLOAK_PASSWORD: admin
      ports:
         - 9081:8080
      depends_on:
         - postgres_dev        
