modelpaths:
   cf_model_path:  "/home/debian/AiDevel_dev/xrayai-webapp/models/cf_model"
   lf_model_path:  "/home/debian/AiDevel_dev/xrayai-webapp/models/lf_model"
   rot_model_path: "/home/debian/AiDevel_dev/xrayai-webapp/models/rot_model"
   ptx_model_path: "/home/debian/AiDevel_dev/xrayai-webapp/models/ptx_model"
   freeair_model_json: "/home/debian/AiDevel_dev/xrayai-webapp/models/pne_model/pne-04162019.json"
   freeair_model_weights: "/home/debian/AiDevel_dev/xrayai-webapp/models/pne_model/pne-04162019.hdf5"
   carina_model_json: "/home/debian/AiDevel_dev/xrayai-webapp/models/carina_model/carina002.json"
   carina_model_weights: "/home/debian/AiDevel_dev/xrayai-webapp/models/carina_model/carina002.hdf5"
   ettube_model_json: "/home/debian/AiDevel_dev/xrayai-webapp/models/ett_model/ett-dec10.json"
   ettube_model_weights: "/home/debian/AiDevel_dev/xrayai-webapp/models/ett_model/ett-dec10.hdf5"
   ettubetip_model_json: "/home/debian/AiDevel_dev/xrayai-webapp/models/etttip_model/etttip-sn480.json"
   ettubetip_model_weights: "/home/debian/AiDevel_dev/xrayai-webapp/models/etttip_model/etttip-sn480.hdf5"


heatmap_path: "/home/debian/AiDevel_dev/xrayai-webapp/heatmapdir"
upload_path: "/home/debian/AiDevel_dev/xrayai-webapp/uploaddir"
grpc_bind_address: "localhost:50052"
app_port: 3002

